### ISSUE TITLE
[REQ] Option to choose bit depth when saving images

### ISSUE THREAD

**Issue by arun54321** [novomesk/gimp-avif-plugin#4]
Could add option to choose bit depth (8,10,12)?

**Comment by novomesk** [comment]
Depth depends on the picture you want to save.

When you have picture with 8bit precision, it is saved as 8bit AVIF.

When you save picture with >= 16bit precision in GIMP, it is saved as 10bit AVIF or 12bit AVIF (if you choose the **Use 12bit Depth** checkbox)

If you work in 8bit precision and you wish to save it as 10bit or 12bit AVIF, change encoding in GIMP to 16bit integer first.
Or if you work in high bit depth and you wish 8bit AVIF only, downgrade the picture to 8bit first.
This is how it works right now.

**Comment by novomesk** [comment]
I am preparing following change:
![avif_plugin](https://user-images.githubusercontent.com/52529860/94846905-2caf0980-0422-11eb-917a-9173643b7bd3.png)

**Comment by novomesk** [comment]
It is implemented. Just a note: Latest code doesn't work with libavif 0.8.1 or older. Fresh snapshot from libavif git master is needed.
